---

all:
  hosts:
    worker01:
      ansible_user: ubuntu
      ansible_host: 3.21.28.158
      ansible_ssh_private_key_file: /home/ubuntu/generic-key.pem
    worker02:
      ansible_user: ubuntu
      ansible_host: 3.145.26.176
      ansible_ssh_private_key_file: /home/ubuntu/generic-key.pem
    worker03:
      ansible_user: ubuntu
      ansible_host: 3.128.33.71
      ansible_ssh_private_key_file: /home/ubuntu/generic-key.pem
